mysite/chat/urls.py
from django.urls import path

from .import views

app_name = 'chat'

urlpatterns = [
    path('chat/', views.chat, name='chat'),
    path('log/', views.log, name='log'),
    # path('chat_log/', views.chat_log, name='chat_log'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls'))
]

mysite/chat/models.py
from django.db import models
import uuid
from django.utils import timezone
# Create your models here.

class Chat_Message(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room = models.CharField('ルーム', blank=True, max_length=50)
    message = models.TextField('メッセージ', blank=True, max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    

    class Meta:
        db_table = 'chat_message'

    

mysite/chat/views.py
import re
from django.shortcuts import render, redirect
from .models import Chat_Message
from django.contrib import messages
from django.db.models import Q
from django.db.models import Count, Max
# Create your views here.

def chat(request):
    chat = Chat_Message.objects.values('room').annotate(count=Count('room')).filter(count__gte=5)
    return render(request, 'chat/chat.html', {'chat': chat})

def log(request):
    chat = Chat_Message.objects.values('room').annotate(count=Count('room')).filter(count__gte=5)
    chat_message_logs = Chat_Message.objects.order_by('-created_at')
    chat_message_room_logs = ''
    room_chat = ''
    """ 検索機能 """
    objects = request.GET.get('input_roomname')
    if objects:
        chat_message_room_logs = chat_message_logs.filter(
            Q(room=objects)
        )
        room_chat = 'ルーム「{}」の検索結果'.format(objects)
    return render(request, 'chat/log.html', {
        'chat_message_logs': chat_message_logs, 'chat_message_room_logs': chat_message_room_logs,
        'room_chat': room_chat, 'chat': chat
        })

def chat_log(request):
    pass

mysite/chat/templates/base.html
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8" />
    <title>My Chat</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> 
    {% block header %}{% endblock %}
    </head>
    <body>
        <br>
        <br>
        <br>
        <div class="container-fluid">
            <h1 class="w-100 text-center shadow-sm" >チャットApp</h1>
            </br>
            </br>
            <div class="w-75 content-center m-auto">
                <p class=" w-50 m-auto text-center shadow-sm" >チャットルームに入ってみんなと話しましょう！</p>
                <p class=" w-50 form-control text-center m-auto shadow-sm" >メッセージ数の多いチャットルーム：{% for c in chat %}{{ c.room }}、{% endfor %}</p>
                <br>
                <br>
                {% block content %}{% endblock %}
                <br>
                <br>
                <div class="w-50 row m-auto">
                    <a class="col  w-auto btn btn-outline-dark shadow-sm"  href={% url 'chat:chat' %}>チャットルームを探す</a>
                    <a class="col w-auto btn btn-outline-dark offset-2 shadow-sm" href={% url 'chat:log' %}>チャットログを検索する</a>
                </div>
                <br>
                <br>
                <p class=" w-75 form-control text-center m-auto" >メッセージ数の多いチャットルーム：{% for c in chat %}{{ c.room }}、{% endfor %}</p>
                <br><br>
            </div>
        </div>
        
    </body>
</html>

mysite/chat/templates/chat/chat.html
{%  extends "base.html" %}
{% block header %}
<style type="text/css">
  input:read-only,
  textarea:read-only {
  }

  #div_join_screen {
  display: flex; /* 子要素をflex配置とする */

  }

  #div_chat_screen {
  display: none; /* 初期状態非表示 */
  }
</style>
{% endblock %}
{% block content %}
<div id="div_container">
  <div id="div_main">
    <div id="div_join_screen">
      <!-- エンターキーによるボタン押下を行うために、<button>ではなく<form>と<input type="submit">を使用。ボタン押下(=submit)時にページリロードが行われないように、onsubmitの設定の最後に"return false;"を追加。-->
      <form class=" w-75 m-auto text-center form-control shadow-sm" onsubmit="onsubmitButton_JoinChat(); return false;">
        <label class="shadow-sm">ユーザーネーム</label>
        <input class=" w-25 m-auto form-control shadow-sm" type="text" id="input_username" placeholder="ユーザーネーム" autofocus /><br/>
        <label class="shadow-sm">ルームネーム</label>
        <input class=" w-50 m-auto form-control shadow-sm" type="text" id="input_roomname" placeholder="ルームネーム" autofocus /><br/>
        <p>ルーム名を検索すると入室ができます。存在しない場合は新しく作成されます。</p>
        <input class=" w-25 m-auto btn btn-outline-dark shadow-sm" type="submit" value="入室" />
      </form>
    </div>
    <div class=" w-75 m-auto" id="div_chat_screen">
      <div class=" w-75 m-auto">
        <button class=" w-25 btn btn-outline-dark shadow-sm" onclick="onclickButton_LeaveChat()">退出</button><br />
      </div>
      <div class=" w-75 m-auto row">
        <label class="col-auto " >ユーザーネーム:</label>
        <input class=" col-auto w-25 form-control-plaintext" type="text" id="text_username" >
        <label class="col-auto" >ルームネーム:</label>
        <input class="col col-auto w-25 form-control-plaintext" type="text" id="text_roomname" readonly="readonly"><br />
        
      </div>
      <!-- enterキーでボタンを押せるように、<button> ではなく <form> と <input type="submit"> を使用。ボタンを押した(=submit)時にページリロードがされないように、 onsubmit の設定の最後に "return false;" を追加。-->
      <form class=" w-75 m-auto text-center form-control shadow-sm" onsubmit="onsubmitButton_Send(); return false;">
        <label>メッセージ</label>
        <textarea class=" w-75 m-auto form-control" type="text" id="input_message" autocomplete="off" autofocus></textarea>
        <input class=" w-25 btn btn-outline-dark" type="submit" value="send" />
      </form>
      <br>
      <br>
      <br>
      <ul class=" list-group border overflow-auto alert alert-secondary" id="list_message">
        {% for message in messages %}
        <li id="db_message"></li><br>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
<script>
  const g_elementDivJoinScreen = document.getElementById("div_join_screen");
  const g_elementDivChatScreen = document.getElementById("div_chat_screen");
  const g_elementInputUserName = document.getElementById("input_username");
  const g_elementInputRoomName = document.getElementById("input_roomname");

  const g_elementTextUserName = document.getElementById("text_username");
  const g_elementTextRoomName = document.getElementById("text_roomname");

  const g_elementInputMessage = document.getElementById("input_message");
  const g_elementListMessage = document.getElementById("list_message");
  const g_elementDbMessage = document.getElementById("db_message");

  //Websocketオブジェクト　送信する形式は指定されている　公文？
  let ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
  const g_socket = new WebSocket(ws_scheme + "://" + window.location.host + "/ws/chat/");

  //「Join Chat」ボタンを押したときに発火
  function onsubmitButton_JoinChat() {
    //ユーザー名を取得する
    let strInputUserName = g_elementInputUserName.value;
    if (!strInputUserName) {
      return;
    }
    // ユーザー名として画面に表示する
    g_elementTextUserName.value = strInputUserName;

    //ルーム名として画面に表示する
    let strInputRoomName = g_elementInputRoomName.value;
    g_elementTextRoomName.value = strInputRoomName;

    // サーバーにはデータタイプとユーザー名とルーム名をjson形式で送信
    g_socket.send(JSON.stringify({ "data_type": "join", "username": strInputUserName, "roomname": strInputRoomName}));
    // チャット画面に切り替える　表示する要素の切り替え
    g_elementDivJoinScreen.style.display="none";  // 参加画面を非表示にする
    g_elementDivChatScreen.style.display="block";  // チャット画面を表示する
  }


  // 「退出」ボタンを押すと発火
  function onclickButton_LeaveChat() {
    // メッセージリストのクリア
    while(g_elementListMessage.firstChild){
      g_elementListMessage.removeChild(g_elementListMessage.firstChild);
    }
    //ユーザー名のクリア
    g_elementTextUserName.value = "";
    // サーバーに"leave"(退出した印)を送信
    g_socket.send(JSON.stringify({ "data_type": "leave"}));

    // 画面の切り替え（ユーザー入力画面に戻す）
    g_elementDivChatScreen.style.display = "none";  // チャット画面の非表示
    g_elementDivJoinScreen.style.display = "flex";  // 参加画面の表示
  }

  //「送信」ボタンを押したときに発火
  function onsubmitButton_Send() {
    // 送信用テキストHTML要素から送られてきたメッセージ文字列の取得
    let strMessage = g_elementInputMessage.value;
    // roomnameの送信
    let strRoomName = g_elementTextRoomName.value;
    
    // 入っていなかった場合はreturnで何もなし
    if (!strMessage) { return;}
    // WebSocket を使ってメッセージを送信  バックエンド側にJSON形式でデータを送信する　リスト型のキーは"message"にしている。
    g_socket.send(JSON.stringify({ "message": strMessage, "roomname": strRoomName }));
    // 送信用テキストHTML要素の中身のクリア
    g_elementInputMessage.value = "";
  }

  // WebSocketからメッセージを受信した時の処理 ////////////
  g_socket.onmessage = (event) => {
    //まだ参加していない時は無視する。
    if(!g_elementTextUserName.value){return;}
    //テキストデータをJSON形式に変換
    let data = JSON.parse(event.data);
    // messageと投稿時間ユーザー名も受け取って表示する。
    let strMessage = data["datetime"] + " - [" + data["username"] + "]" + data["message"];
    /// DBに元々入っていた値を全て取得する。そしてULタグにLIタグで内包する。
    // let db_strMessage = data["db_message"]
    // 拡散されたメッセージをメッセージリストに追加
    //メッセージの入れ物として新たにliタグのエレメントの作成
    let elementLi = document.createElement("li");
    // let elementDb = document.createElement("li");
    // 作成したエレメントのtextContentにキーが"message"の値が入った変数を代入する。
    elementLi.textContent = strMessage;
    // ulエレメントの中に今作成したliエレメントを内包する。
    g_elementListMessage.prepend(elementLi); // リストの一番上に追加したいとき
    // g_elementListMessage.prepend(elementLi); // リストの一番下に追加したいとき

  };

  // WebSocketクローズ時の処理
  g_socket.onclose = (event) => {
    // ウェブページを閉じたとき以外のWebSocketクローズは想定外
    console.error("Unexpected : Chat socket closed");
  };

  
</script>
{% endblock %}

mysite/chat/templates/chat/chat_log.html
no use 
チャットログ
{% for message in context %}
<ul>
    <li>a{{ message.chat_message }}</li>
</ul>
{% endfor %}

mysite/chat/templates/chat/log.html
{%  extends "base.html" %}
{% block header %}
{% endblock %}
{% block content %}

<div>
    <div class=" w-75 m-auto">
        <form lass="w-50 m-auto form-control shadow-sm" action="{% url 'chat:log' %}" method="GET">
            <label class="w-100 shadow-sm m-auto text-center">ルームネーム</label>
            <input class=" w-25 m-auto form-control shadow-sm" type="text" id="input_roomname" name="input_roomname" placeholder="ルームネーム" autofocus /><br />
            <p class=" w-75 m-auto text-center shadow-sm" >ルーム名を検索するとメッセージ過去のログを見ることができます。</p><br />
            <input class="w-100 shadow-sm m-auto text-center btn btn-outline-dark " type="submit" value="検索" />
        </form>
        <br>
        <a class=" m-auto content-center  btn btn-outline-dark shadow-sm" href={% url 'chat:chat' %}>チャットルームに入る</a>
        <a class="2 m-auto btn btn-outline-dark shadow-sm" href={% url 'chat:log' %}>更新</a>
    </div>
    <div>
        <div class=" w-75 m-auto form-group">
            <h3>{{ room_chat }}</h3>
            {% for message in chat_message_room_logs  %}
            <ul class="form-control border border-right-0 shadow-sm" style="list-style: none;" >
                <textarea class="form-control border-bottom shadow-sm" style="width: 100%;">  {{ forloop.counter }}．ルーム({{message.room}})：{{ message.message }}</textarea>
                <li>　{{ message.created_at }}</li> 
            </ul>
            {% endfor %}
        </div>
        <div class=" w-75 m-auto form-group">
            <h3>全ルームの最新チャット</h3>
            {% for message in chat_message_logs|slice:15 %}
            <ul class="form-control border border-right-0 shadow-sm" style="list-style: none;" >
                <textarea class="form-control border-bottom shadow-sm" style="width: 100%;"> {{ forloop.counter }}．({{message.room}})：{{ message.message }}</textarea>
                <li>　{{ message.created_at }}</li> 
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
